### ISSUE TITLE
Add Hamburger Menu

### ISSUE THREAD

**Issue by tysmith86** [Waxhoya/Rose#14]
Umm..title says it all.

**Comment by tysmith86** [comment]
Added reddit menu instead of hamburger menu. AJ will take care of getting the hamburger menu into his page tonight. It is working on hover, and only displaying when below the width threshold.

**Comment by Waxhoya** [comment]
resolved in pull of class-10 branch
https://github.com/Waxhoya/Portfolio/pull/19
